### ISSUE TITLE
The mean and variance of each sub-distribution in the mixed Gaussian

### ISSUE THREAD

**Issue by xiaoquexingchen** [h-munakata/VB-GMM#1]
Hi:
    Do frame_mu, frame_Sigma, and frame_mixture_C in this code refer to the mean, variance and mixing ratio of the mixed Gaussian neutron distribution? Why is the result wrong when outputting these values. Hope to get your help and look forward to your reply.

**Comment by h-munakata** [comment]
Hi :）

>>Do frame_mu, frame_Sigma, and frame_mixture_C in this code refer to the mean, variance and mixing ratio of the mixed Gaussian neutron distribution? 

That's right. Each value of frame_mu, Sigma and C are expected values of mean, variance and mixing ratio of posterior distribution.
"frame_X" stores the values for each step as List format for drawing an animation.

>>Why is the result wrong when outputting these values.
If you want to print the final value of estimation, code it as follows
$ print(frame_mu[-1])
It shows the means of each mixture.

**Comment by xiaoquexingchen** [comment]
Hi:
    I still have a problem because the sample has only 5 classes, but after initializing k=10, the mean and variance of the final output are both 10 groups, but the mean and variance that are set roughly correspond to the set mean and variance and it is always less than 5. Piece. How should this be solved? Looking forward to your reply, thank you!

**Comment by h-munakata** [comment]
If you want the estimated number to match the original class number, you should set the appropriate prior distribution.

If you set alpha as the large value, classes tend to be contributed by the data, namely,
the number of the valid classes tend to increase.
On the other hand, the class which none of the data contribute to will degenerate into the prior distribution.

My implement doesn't remove classes explaining none of the data.
So the number of output corresponding to k you set is correct.

**Comment by xiaoquexingchen** [comment]
Hi:
    Because the input data is two-dimensional, how do I want to input one-dimensional data for testing, what should I adjust? I look forward to your reply, thank you!
